version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: devops-postgres
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops
      POSTGRES_DB: devops_platform
    ports:
      - "5432:5432"
    volumes:
      - ../services/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend_v1:
    build: ../services/frontend-react
    container_name: frontend_v1
    ports:
      - "3000:3000"
    depends_on:
      - backend_v1

  frontend_v2:
    build: ../services/frontend-react
    container_name: frontend_v2
    ports:
      - "3001:3000"
    depends_on:
      - backend_v2

  backend_v1:
    build: ../services/backend-fastapi
    container_name: backend_v1
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: devops
      DB_PASSWORD: devops
      DB_NAME: devops_platform

  backend_v2:
    build: ../services/backend-fastapi
    container_name: backend_v2
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: devops
      DB_PASSWORD: devops
      DB_NAME: devops_platform

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend_v1
      - frontend_v2
      - backend_v1
      - backend_v2