events {}

http {
    upstream frontend_active {
        server frontend_v1:3000;
        # server frontend_v2:3000;
    }

    upstream backend_active {
        server backend_v1:8000;
        # server backend_v2:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://frontend_active;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/ {
            proxy_pass http://backend_active/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}


# events {}

# http {
#     upstream frontend {
#         server frontend:3000;
#     }

#     upstream backend {
#         server backend:8000;
#     }

#     server {
#         listen 80;

#         location / {
#             proxy_pass http://frontend;
#         }

#         location /api/ {
#             proxy_pass http://backend/;
#         }
#     }
# }