name: DevOps Platform CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Backend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-fastapi ./services/backend-fastapi

      - name: Build Frontend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-react ./services/frontend-react

      - name: Push Backend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend-fastapi

      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend-react

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Pull latest images
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend-fastapi
            docker pull ${{ secrets.DOCKER_USERNAME }}/frontend-react

            docker rm -f backend-new || true
            docker rm -f frontend-new || true

            # ---------------- BACKEND ----------------
            docker run -d -p 8001:8000 --name backend-new ${{ secrets.DOCKER_USERNAME }}/backend-fastapi
            sleep 10

            # validate
            docker ps | grep backend-new

            if [ $? -ne 0 ]; then
              echo "Backend failed"
              exit 1
            fi

            # DEBUG
            docker ps
            docker stop backend-fastapi || true
            docker rm backend-fastapi || true

            docker rename backend-new backend-fastapi

            # ---------------- FRONTEND ----------------
            docker run -d -p 3001:3000 --name frontend-new ${{ secrets.DOCKER_USERNAME }}/frontend-react
            sleep 10
            # DEBUG: show running containers
            docker ps

            # ✅ VALIDATE new container
            docker ps | grep frontend-new

            # If NOT running → EXIT (do NOT kill old)
            if [ $? -ne 0 ]; then
              echo "New container failed. Aborting deploy."
              exit 1
            fi

            # If success → remove old
            docker stop frontend-react || true
            docker rm frontend-react || true

            # Rename new → stable name
            docker rename frontend-new frontend-react
